#!/bin/bash

# Analyze files with jpylyzer
# Author: Johan van der Knijff (adapted from script by John Lehr)

title="jpylyzer output"

jpylyzer "$@" | yad --text-info \
	--title "$title" \
	--width=640 \
	--height=480
exit 0

