#!/bin/bash

# Extract text from file with Apache Tika
# Author: Johan van der Knijff (adapted from script by John Lehr)

title="tika output"

tika --text "$1" | yad --text-info \
	--title "$title" \
	--width=640 \
	--height=480
exit 0

