#!/bin/bash

# Convert Markdown file to user-defined output format using pandoc

fileIn="$1"

# Get script location
scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

userInput=$(yad --width=400 --title="Convert from Markdown" --text="Settings:" \
--form \
--field="Input format":CB \
'markdown!markdown_phpextra' \
--field="Output format":CB \
'docx!odt!html5!mediawiki')

# Parse yad output into variables
fmtIn="$(cut -d'|' -f1 <<<$userInput)"
fmtOut="$(cut -d'|' -f2 <<<$userInput)"

# Set output file extension
case $fmtOut in
    docx) extensionOut="docx" ;;
    odt) extensionOut=odt ;;
    html5) extensionOut=html ;;
    mediawiki) extensionOut=wiki ;;
esac

# Input file basename, extension removed
bName=$(basename "$fileIn" | cut -f 1 -d '.')

# Output file name
fileOut=$bName.$extensionOut

# Convert with Pandoc. Use --reference-doc (template) option if input format is docx

if [ "$fmtOut" == "docx" ] ; then
    # Template MS Word file (in same dir as script)
    referenceDoc=$scriptDir/.templates/reference.docx
    pandoc --reference-doc $referenceDoc -f $fmtIn -s "$fileIn" -t $fmtOut -o "$fileOut"
elif [ "$fmtOut" == "odt" ] ; then
    referenceDoc=$scriptDir/.templates/reference.odt
    pandoc --reference-doc $referenceDoc -f $fmtIn -s "$fileIn" -t $fmtOut -o "$fileOut"
else
    pandoc -f $fmtIn -s "$fileIn" -t $fmtOut -o "$fileOut"
fi
