#!/bin/bash

# Analyze file with pdfinfor
# Author: Johan van der Knijff (adapted from script by John Lehr)

title="pdfinfo output"

pdfinfo -meta "$1" | yad --text-info \
	--title "$title" \
	--width=640 \
	--height=480
exit 0

