#!/bin/bash
#: Title		: Show Mime Type (mime)
#: Date			: 2010-05-11
#: Author		: "John Lehr" <slo.sleuth@gmail.com>
#: Version		: 1.0
#: Description	: Display file mime type

file -i "$@" | yad --text-info \
	--title "Show File Type" \
	--width=640 \
	--height=480

exit 0
 

