#!/bin/bash

# Establish Mimetype of a file with Apache Tika
# Author: Johan van der Knijff (adapted from script by John Lehr)

title="tika output"

tika -d "$1" | yad --text-info \
	--title "$title" \
	--width=640 \
	--height=480
exit 0

